version: '3'
services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    tty: true
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - sonarnet
    ports:
      - "9000:9000"
  
  networks:
  sonarnet:
    driver: bridge
    name: sonarnet